# coding: utf-8

"""
    Cerebral API

    The Wdata Preparation API allow users to import data sets from their source system, tag, organize, manipulate, share, export, and query against the data  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: scoutteam@workiva.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.select_list_management_api import SelectListManagementApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSelectListManagementApi(unittest.TestCase):
    """SelectListManagementApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.select_list_management_api.SelectListManagementApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_select_list_using_post(self):
        """Test case for create_select_list_using_post

        Create a new select list  # noqa: E501
        """
        pass

    def test_delete_using_delete(self):
        """Test case for delete_using_delete

        Delete a single select list  # noqa: E501
        """
        pass

    def test_get_select_list_using_get(self):
        """Test case for get_select_list_using_get

        Retrieve a single select list  # noqa: E501
        """
        pass

    def test_list_select_lists_using_get(self):
        """Test case for list_select_lists_using_get

        Retrieve a list of select lists  # noqa: E501
        """
        pass

    def test_update_select_list_using_put(self):
        """Test case for update_select_list_using_put

        Update a single select list  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
