# coding: utf-8

"""
    Cerebral API

    The Wdata Preparation API allow users to import data sets from their source system, tag, organize, manipulate, share, export, and query against the data  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: scoutteam@workiva.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.table_management_api import TableManagementApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTableManagementApi(unittest.TestCase):
    """TableManagementApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.table_management_api.TableManagementApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_table_using_post(self):
        """Test case for create_table_using_post

        Create a new table  # noqa: E501
        """
        pass

    def test_delete_table_using_delete(self):
        """Test case for delete_table_using_delete

        Delete a single table  # noqa: E501
        """
        pass

    def test_get_dependents_using_get(self):
        """Test case for get_dependents_using_get

        Retrieve a list of dependents  # noqa: E501
        """
        pass

    def test_get_import_info_using_get(self):
        """Test case for get_import_info_using_get

        Retrieve import information  # noqa: E501
        """
        pass

    def test_get_table_using_get(self):
        """Test case for get_table_using_get

        Retrieve a single table  # noqa: E501
        """
        pass

    def test_get_tables_using_get(self):
        """Test case for get_tables_using_get

        Retrieve a list of tables  # noqa: E501
        """
        pass

    def test_import_file_using_post(self):
        """Test case for import_file_using_post

        Import a single file  # noqa: E501
        """
        pass

    def test_import_from_spreadsheets_using_post(self):
        """Test case for import_from_spreadsheets_using_post

        Import from spreadsheets  # noqa: E501
        """
        pass

    def test_unimport_file_using_delete(self):
        """Test case for unimport_file_using_delete

        Unimport a single file  # noqa: E501
        """
        pass

    def test_update_table_using_put(self):
        """Test case for update_table_using_put

        Update a single table  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
