# coding: utf-8

"""
    Cerebral API

    The Wdata Preparation API allow users to import data sets from their source system, tag, organize, manipulate, share, export, and query against the data  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: scoutteam@workiva.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.parameter_management_api import ParameterManagementApi  # noqa: E501
from swagger_client.rest import ApiException


class TestParameterManagementApi(unittest.TestCase):
    """ParameterManagementApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.parameter_management_api.ParameterManagementApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_parameter_using_post(self):
        """Test case for create_parameter_using_post

        Create parameter  # noqa: E501
        """
        pass

    def test_delete_parameter_using_delete(self):
        """Test case for delete_parameter_using_delete

        Delete Parameter  # noqa: E501
        """
        pass

    def test_get_parameter_using_get(self):
        """Test case for get_parameter_using_get

        Get Parameter  # noqa: E501
        """
        pass

    def test_list_parameters_using_get(self):
        """Test case for list_parameters_using_get

        Get Parameters  # noqa: E501
        """
        pass

    def test_update_parameter_using_put(self):
        """Test case for update_parameter_using_put

        Update Parameter  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
