# coding: utf-8

"""
    Cerebral API

    The Wdata Preparation API allow users to import data sets from their source system, tag, organize, manipulate, share, export, and query against the data  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: scoutteam@workiva.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.folder_management_api import FolderManagementApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFolderManagementApi(unittest.TestCase):
    """FolderManagementApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.folder_management_api.FolderManagementApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_folder_using_post(self):
        """Test case for create_folder_using_post

        Create a new folder  # noqa: E501
        """
        pass

    def test_delete_folder_using_delete(self):
        """Test case for delete_folder_using_delete

        Delete a single folder  # noqa: E501
        """
        pass

    def test_get_folder_using_get(self):
        """Test case for get_folder_using_get

        Retrieve a single folder  # noqa: E501
        """
        pass

    def test_list_children_using_get(self):
        """Test case for list_children_using_get

        Retrieve list of folder contents  # noqa: E501
        """
        pass

    def test_list_folders_using_get(self):
        """Test case for list_folders_using_get

        Retrieve a list of folders  # noqa: E501
        """
        pass

    def test_search_using_get(self):
        """Test case for search_using_get

        Search  # noqa: E501
        """
        pass

    def test_set_children_using_post(self):
        """Test case for set_children_using_post

        Move content into a folder  # noqa: E501
        """
        pass

    def test_update_folder_using_put(self):
        """Test case for update_folder_using_put

        Update a single folder  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
