# coding: utf-8

"""
    Cerebral API

    The Wdata Preparation API allow users to import data sets from their source system, tag, organize, manipulate, share, export, and query against the data  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: scoutteam@workiva.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.utilities_api import UtilitiesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUtilitiesApi(unittest.TestCase):
    """UtilitiesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.utilities_api.UtilitiesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_parse_date_using_post(self):
        """Test case for parse_date_using_post

        Parse a date  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
