# coding: utf-8

"""
    Cerebral API

    The Wdata Preparation API allow users to import data sets from their source system, tag, organize, manipulate, share, export, and query against the data  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: scoutteam@workiva.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.map_ofstring_andstring import MapOfstringAndstring  # noqa: E501
from swagger_client.rest import ApiException


class TestMapOfstringAndstring(unittest.TestCase):
    """MapOfstringAndstring unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMapOfstringAndstring(self):
        """Test MapOfstringAndstring"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.map_ofstring_andstring.MapOfstringAndstring()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
