# coding: utf-8

"""
    Cerebral API

    The Wdata Preparation API allow users to import data sets from their source system, tag, organize, manipulate, share, export, and query against the data  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: scoutteam@workiva.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class ConnectionRunDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'connection_id': 'str',
        'created': 'datetime',
        'created_by': 'str',
        'destination_parameters': 'object',
        'destination_status': 'str',
        'error': 'str',
        'job_id': 'str',
        'source_parameters': 'object',
        'source_status': 'str',
        'updated': 'datetime'
    }

    attribute_map = {
        'connection_id': 'connectionId',
        'created': 'created',
        'created_by': 'createdBy',
        'destination_parameters': 'destinationParameters',
        'destination_status': 'destinationStatus',
        'error': 'error',
        'job_id': 'jobId',
        'source_parameters': 'sourceParameters',
        'source_status': 'sourceStatus',
        'updated': 'updated'
    }

    def __init__(self, connection_id=None, created=None, created_by=None, destination_parameters=None, destination_status=None, error=None, job_id=None, source_parameters=None, source_status=None, updated=None, _configuration=None):  # noqa: E501
        """ConnectionRunDto - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._connection_id = None
        self._created = None
        self._created_by = None
        self._destination_parameters = None
        self._destination_status = None
        self._error = None
        self._job_id = None
        self._source_parameters = None
        self._source_status = None
        self._updated = None
        self.discriminator = None

        if connection_id is not None:
            self.connection_id = connection_id
        if created is not None:
            self.created = created
        if created_by is not None:
            self.created_by = created_by
        if destination_parameters is not None:
            self.destination_parameters = destination_parameters
        if destination_status is not None:
            self.destination_status = destination_status
        if error is not None:
            self.error = error
        if job_id is not None:
            self.job_id = job_id
        if source_parameters is not None:
            self.source_parameters = source_parameters
        if source_status is not None:
            self.source_status = source_status
        if updated is not None:
            self.updated = updated

    @property
    def connection_id(self):
        """Gets the connection_id of this ConnectionRunDto.  # noqa: E501

        The unique ID of the connection  # noqa: E501

        :return: The connection_id of this ConnectionRunDto.  # noqa: E501
        :rtype: str
        """
        return self._connection_id

    @connection_id.setter
    def connection_id(self, connection_id):
        """Sets the connection_id of this ConnectionRunDto.

        The unique ID of the connection  # noqa: E501

        :param connection_id: The connection_id of this ConnectionRunDto.  # noqa: E501
        :type: str
        """

        self._connection_id = connection_id

    @property
    def created(self):
        """Gets the created of this ConnectionRunDto.  # noqa: E501

        When the connection was created, as a datetime  # noqa: E501

        :return: The created of this ConnectionRunDto.  # noqa: E501
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this ConnectionRunDto.

        When the connection was created, as a datetime  # noqa: E501

        :param created: The created of this ConnectionRunDto.  # noqa: E501
        :type: datetime
        """

        self._created = created

    @property
    def created_by(self):
        """Gets the created_by of this ConnectionRunDto.  # noqa: E501

        The ID of the user that created the connection  # noqa: E501

        :return: The created_by of this ConnectionRunDto.  # noqa: E501
        :rtype: str
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this ConnectionRunDto.

        The ID of the user that created the connection  # noqa: E501

        :param created_by: The created_by of this ConnectionRunDto.  # noqa: E501
        :type: str
        """

        self._created_by = created_by

    @property
    def destination_parameters(self):
        """Gets the destination_parameters of this ConnectionRunDto.  # noqa: E501

        Any parameters provided to the destination  # noqa: E501

        :return: The destination_parameters of this ConnectionRunDto.  # noqa: E501
        :rtype: object
        """
        return self._destination_parameters

    @destination_parameters.setter
    def destination_parameters(self, destination_parameters):
        """Sets the destination_parameters of this ConnectionRunDto.

        Any parameters provided to the destination  # noqa: E501

        :param destination_parameters: The destination_parameters of this ConnectionRunDto.  # noqa: E501
        :type: object
        """

        self._destination_parameters = destination_parameters

    @property
    def destination_status(self):
        """Gets the destination_status of this ConnectionRunDto.  # noqa: E501

        The run status of the destination  # noqa: E501

        :return: The destination_status of this ConnectionRunDto.  # noqa: E501
        :rtype: str
        """
        return self._destination_status

    @destination_status.setter
    def destination_status(self, destination_status):
        """Sets the destination_status of this ConnectionRunDto.

        The run status of the destination  # noqa: E501

        :param destination_status: The destination_status of this ConnectionRunDto.  # noqa: E501
        :type: str
        """
        allowed_values = ["not_started", "running", "complete", "error", "cancelled"]  # noqa: E501
        if (self._configuration.client_side_validation and
                destination_status not in allowed_values):
            raise ValueError(
                "Invalid value for `destination_status` ({0}), must be one of {1}"  # noqa: E501
                .format(destination_status, allowed_values)
            )

        self._destination_status = destination_status

    @property
    def error(self):
        """Gets the error of this ConnectionRunDto.  # noqa: E501

        An error, if encountered, while initiating the job  # noqa: E501

        :return: The error of this ConnectionRunDto.  # noqa: E501
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this ConnectionRunDto.

        An error, if encountered, while initiating the job  # noqa: E501

        :param error: The error of this ConnectionRunDto.  # noqa: E501
        :type: str
        """

        self._error = error

    @property
    def job_id(self):
        """Gets the job_id of this ConnectionRunDto.  # noqa: E501

        The unique ID of the job  # noqa: E501

        :return: The job_id of this ConnectionRunDto.  # noqa: E501
        :rtype: str
        """
        return self._job_id

    @job_id.setter
    def job_id(self, job_id):
        """Sets the job_id of this ConnectionRunDto.

        The unique ID of the job  # noqa: E501

        :param job_id: The job_id of this ConnectionRunDto.  # noqa: E501
        :type: str
        """

        self._job_id = job_id

    @property
    def source_parameters(self):
        """Gets the source_parameters of this ConnectionRunDto.  # noqa: E501

        Any parameters provided to the source  # noqa: E501

        :return: The source_parameters of this ConnectionRunDto.  # noqa: E501
        :rtype: object
        """
        return self._source_parameters

    @source_parameters.setter
    def source_parameters(self, source_parameters):
        """Sets the source_parameters of this ConnectionRunDto.

        Any parameters provided to the source  # noqa: E501

        :param source_parameters: The source_parameters of this ConnectionRunDto.  # noqa: E501
        :type: object
        """

        self._source_parameters = source_parameters

    @property
    def source_status(self):
        """Gets the source_status of this ConnectionRunDto.  # noqa: E501

        The run status of the source  # noqa: E501

        :return: The source_status of this ConnectionRunDto.  # noqa: E501
        :rtype: str
        """
        return self._source_status

    @source_status.setter
    def source_status(self, source_status):
        """Sets the source_status of this ConnectionRunDto.

        The run status of the source  # noqa: E501

        :param source_status: The source_status of this ConnectionRunDto.  # noqa: E501
        :type: str
        """
        allowed_values = ["not_started", "running", "complete", "error", "cancelled"]  # noqa: E501
        if (self._configuration.client_side_validation and
                source_status not in allowed_values):
            raise ValueError(
                "Invalid value for `source_status` ({0}), must be one of {1}"  # noqa: E501
                .format(source_status, allowed_values)
            )

        self._source_status = source_status

    @property
    def updated(self):
        """Gets the updated of this ConnectionRunDto.  # noqa: E501

        When the connection was updated, as a datetime  # noqa: E501

        :return: The updated of this ConnectionRunDto.  # noqa: E501
        :rtype: datetime
        """
        return self._updated

    @updated.setter
    def updated(self, updated):
        """Sets the updated of this ConnectionRunDto.

        When the connection was updated, as a datetime  # noqa: E501

        :param updated: The updated of this ConnectionRunDto.  # noqa: E501
        :type: datetime
        """

        self._updated = updated

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConnectionRunDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConnectionRunDto):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ConnectionRunDto):
            return True

        return self.to_dict() != other.to_dict()
