# coding: utf-8

"""
    Cerebral API

    The Wdata Preparation API allow users to import data sets from their source system, tag, organize, manipulate, share, export, and query against the data  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: scoutteam@workiva.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class FolderDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'created': 'datetime',
        'description': 'str',
        'id': 'str',
        'name': 'str',
        'parent_id': 'str',
        'updated': 'datetime',
        'user_id': 'str',
        'version': 'int'
    }

    attribute_map = {
        'created': 'created',
        'description': 'description',
        'id': 'id',
        'name': 'name',
        'parent_id': 'parentId',
        'updated': 'updated',
        'user_id': 'userId',
        'version': 'version'
    }

    def __init__(self, created=None, description=None, id=None, name=None, parent_id=None, updated=None, user_id=None, version=None, _configuration=None):  # noqa: E501
        """FolderDto - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._created = None
        self._description = None
        self._id = None
        self._name = None
        self._parent_id = None
        self._updated = None
        self._user_id = None
        self._version = None
        self.discriminator = None

        if created is not None:
            self.created = created
        if description is not None:
            self.description = description
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if parent_id is not None:
            self.parent_id = parent_id
        if updated is not None:
            self.updated = updated
        if user_id is not None:
            self.user_id = user_id
        if version is not None:
            self.version = version

    @property
    def created(self):
        """Gets the created of this FolderDto.  # noqa: E501

        When the entity was created  # noqa: E501

        :return: The created of this FolderDto.  # noqa: E501
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this FolderDto.

        When the entity was created  # noqa: E501

        :param created: The created of this FolderDto.  # noqa: E501
        :type: datetime
        """

        self._created = created

    @property
    def description(self):
        """Gets the description of this FolderDto.  # noqa: E501

        A description of the folder  # noqa: E501

        :return: The description of this FolderDto.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this FolderDto.

        A description of the folder  # noqa: E501

        :param description: The description of this FolderDto.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                description is not None and len(description) > 1024):
            raise ValueError("Invalid value for `description`, length must be less than or equal to `1024`")  # noqa: E501
        if (self._configuration.client_side_validation and
                description is not None and len(description) < 0):
            raise ValueError("Invalid value for `description`, length must be greater than or equal to `0`")  # noqa: E501

        self._description = description

    @property
    def id(self):
        """Gets the id of this FolderDto.  # noqa: E501

        The entity's unique identifier  # noqa: E501

        :return: The id of this FolderDto.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this FolderDto.

        The entity's unique identifier  # noqa: E501

        :param id: The id of this FolderDto.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this FolderDto.  # noqa: E501

        The name of the folder  # noqa: E501

        :return: The name of this FolderDto.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this FolderDto.

        The name of the folder  # noqa: E501

        :param name: The name of this FolderDto.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                name is not None and len(name) > 255):
            raise ValueError("Invalid value for `name`, length must be less than or equal to `255`")  # noqa: E501
        if (self._configuration.client_side_validation and
                name is not None and len(name) < 0):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `0`")  # noqa: E501

        self._name = name

    @property
    def parent_id(self):
        """Gets the parent_id of this FolderDto.  # noqa: E501

        The ID of the folder to which this folder belongs. This can be null if the folder is not in another folder.  # noqa: E501

        :return: The parent_id of this FolderDto.  # noqa: E501
        :rtype: str
        """
        return self._parent_id

    @parent_id.setter
    def parent_id(self, parent_id):
        """Sets the parent_id of this FolderDto.

        The ID of the folder to which this folder belongs. This can be null if the folder is not in another folder.  # noqa: E501

        :param parent_id: The parent_id of this FolderDto.  # noqa: E501
        :type: str
        """

        self._parent_id = parent_id

    @property
    def updated(self):
        """Gets the updated of this FolderDto.  # noqa: E501

        When the entity was last updated  # noqa: E501

        :return: The updated of this FolderDto.  # noqa: E501
        :rtype: datetime
        """
        return self._updated

    @updated.setter
    def updated(self, updated):
        """Sets the updated of this FolderDto.

        When the entity was last updated  # noqa: E501

        :param updated: The updated of this FolderDto.  # noqa: E501
        :type: datetime
        """

        self._updated = updated

    @property
    def user_id(self):
        """Gets the user_id of this FolderDto.  # noqa: E501

        The owner of the entity  # noqa: E501

        :return: The user_id of this FolderDto.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this FolderDto.

        The owner of the entity  # noqa: E501

        :param user_id: The user_id of this FolderDto.  # noqa: E501
        :type: str
        """

        self._user_id = user_id

    @property
    def version(self):
        """Gets the version of this FolderDto.  # noqa: E501

        The version of the current representation of the entity  # noqa: E501

        :return: The version of this FolderDto.  # noqa: E501
        :rtype: int
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this FolderDto.

        The version of the current representation of the entity  # noqa: E501

        :param version: The version of this FolderDto.  # noqa: E501
        :type: int
        """

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FolderDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FolderDto):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, FolderDto):
            return True

        return self.to_dict() != other.to_dict()
