# coding: utf-8

"""
    Cerebral API

    The Wdata Preparation API allow users to import data sets from their source system, tag, organize, manipulate, share, export, and query against the data  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: scoutteam@workiva.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class TokenDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'created': 'datetime',
        'id': 'str',
        'object_id': 'str',
        'updated': 'datetime',
        'use_flat_key': 'bool',
        'user_id': 'str',
        'version': 'int'
    }

    attribute_map = {
        'created': 'created',
        'id': 'id',
        'object_id': 'objectId',
        'updated': 'updated',
        'use_flat_key': 'useFlatKey',
        'user_id': 'userId',
        'version': 'version'
    }

    def __init__(self, created=None, id=None, object_id=None, updated=None, use_flat_key=None, user_id=None, version=None, _configuration=None):  # noqa: E501
        """TokenDto - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._created = None
        self._id = None
        self._object_id = None
        self._updated = None
        self._use_flat_key = None
        self._user_id = None
        self._version = None
        self.discriminator = None

        if created is not None:
            self.created = created
        if id is not None:
            self.id = id
        if object_id is not None:
            self.object_id = object_id
        if updated is not None:
            self.updated = updated
        if use_flat_key is not None:
            self.use_flat_key = use_flat_key
        if user_id is not None:
            self.user_id = user_id
        if version is not None:
            self.version = version

    @property
    def created(self):
        """Gets the created of this TokenDto.  # noqa: E501

        When the entity was created  # noqa: E501

        :return: The created of this TokenDto.  # noqa: E501
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this TokenDto.

        When the entity was created  # noqa: E501

        :param created: The created of this TokenDto.  # noqa: E501
        :type: datetime
        """

        self._created = created

    @property
    def id(self):
        """Gets the id of this TokenDto.  # noqa: E501

        The entity's unique identifier  # noqa: E501

        :return: The id of this TokenDto.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TokenDto.

        The entity's unique identifier  # noqa: E501

        :param id: The id of this TokenDto.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def object_id(self):
        """Gets the object_id of this TokenDto.  # noqa: E501

        The object's unique identifier  # noqa: E501

        :return: The object_id of this TokenDto.  # noqa: E501
        :rtype: str
        """
        return self._object_id

    @object_id.setter
    def object_id(self, object_id):
        """Sets the object_id of this TokenDto.

        The object's unique identifier  # noqa: E501

        :param object_id: The object_id of this TokenDto.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                object_id is not None and len(object_id) > 32):
            raise ValueError("Invalid value for `object_id`, length must be less than or equal to `32`")  # noqa: E501
        if (self._configuration.client_side_validation and
                object_id is not None and len(object_id) < 0):
            raise ValueError("Invalid value for `object_id`, length must be greater than or equal to `0`")  # noqa: E501

        self._object_id = object_id

    @property
    def updated(self):
        """Gets the updated of this TokenDto.  # noqa: E501

        When the entity was last updated  # noqa: E501

        :return: The updated of this TokenDto.  # noqa: E501
        :rtype: datetime
        """
        return self._updated

    @updated.setter
    def updated(self, updated):
        """Sets the updated of this TokenDto.

        When the entity was last updated  # noqa: E501

        :param updated: The updated of this TokenDto.  # noqa: E501
        :type: datetime
        """

        self._updated = updated

    @property
    def use_flat_key(self):
        """Gets the use_flat_key of this TokenDto.  # noqa: E501

        Create token using flat query results key; Ignored unless true.  # noqa: E501

        :return: The use_flat_key of this TokenDto.  # noqa: E501
        :rtype: bool
        """
        return self._use_flat_key

    @use_flat_key.setter
    def use_flat_key(self, use_flat_key):
        """Sets the use_flat_key of this TokenDto.

        Create token using flat query results key; Ignored unless true.  # noqa: E501

        :param use_flat_key: The use_flat_key of this TokenDto.  # noqa: E501
        :type: bool
        """

        self._use_flat_key = use_flat_key

    @property
    def user_id(self):
        """Gets the user_id of this TokenDto.  # noqa: E501

        The owner of the entity  # noqa: E501

        :return: The user_id of this TokenDto.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this TokenDto.

        The owner of the entity  # noqa: E501

        :param user_id: The user_id of this TokenDto.  # noqa: E501
        :type: str
        """

        self._user_id = user_id

    @property
    def version(self):
        """Gets the version of this TokenDto.  # noqa: E501

        The version of the current representation of the entity  # noqa: E501

        :return: The version of this TokenDto.  # noqa: E501
        :rtype: int
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this TokenDto.

        The version of the current representation of the entity  # noqa: E501

        :param version: The version of this TokenDto.  # noqa: E501
        :type: int
        """

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TokenDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TokenDto):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TokenDto):
            return True

        return self.to_dict() != other.to_dict()
