# coding: utf-8

"""
    Cerebral API

    The Wdata Preparation API allow users to import data sets from their source system, tag, organize, manipulate, share, export, and query against the data  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: scoutteam@workiva.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class UniqueConstraintDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'description': 'str',
        'id': 'str',
        'name': 'str',
        'table_id': 'str',
        'values': 'list[str]'
    }

    attribute_map = {
        'description': 'description',
        'id': 'id',
        'name': 'name',
        'table_id': 'tableId',
        'values': 'values'
    }

    def __init__(self, description=None, id=None, name=None, table_id=None, values=None, _configuration=None):  # noqa: E501
        """UniqueConstraintDto - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._description = None
        self._id = None
        self._name = None
        self._table_id = None
        self._values = None
        self.discriminator = None

        if description is not None:
            self.description = description
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if table_id is not None:
            self.table_id = table_id
        if values is not None:
            self.values = values

    @property
    def description(self):
        """Gets the description of this UniqueConstraintDto.  # noqa: E501

        Description of this unique constraint. Max length: 1024  # noqa: E501

        :return: The description of this UniqueConstraintDto.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this UniqueConstraintDto.

        Description of this unique constraint. Max length: 1024  # noqa: E501

        :param description: The description of this UniqueConstraintDto.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                description is not None and len(description) > 1024):
            raise ValueError("Invalid value for `description`, length must be less than or equal to `1024`")  # noqa: E501
        if (self._configuration.client_side_validation and
                description is not None and len(description) < 0):
            raise ValueError("Invalid value for `description`, length must be greater than or equal to `0`")  # noqa: E501

        self._description = description

    @property
    def id(self):
        """Gets the id of this UniqueConstraintDto.  # noqa: E501

        Id of the unique constraint  # noqa: E501

        :return: The id of this UniqueConstraintDto.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this UniqueConstraintDto.

        Id of the unique constraint  # noqa: E501

        :param id: The id of this UniqueConstraintDto.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                id is not None and len(id) > 100):
            raise ValueError("Invalid value for `id`, length must be less than or equal to `100`")  # noqa: E501
        if (self._configuration.client_side_validation and
                id is not None and len(id) < 0):
            raise ValueError("Invalid value for `id`, length must be greater than or equal to `0`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this UniqueConstraintDto.  # noqa: E501

        Name of this unique constraint. Max length: 100  # noqa: E501

        :return: The name of this UniqueConstraintDto.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this UniqueConstraintDto.

        Name of this unique constraint. Max length: 100  # noqa: E501

        :param name: The name of this UniqueConstraintDto.  # noqa: E501
        :type: str
        """
        allowed_values = ["key_columns"]  # noqa: E501
        if (self._configuration.client_side_validation and
                name not in allowed_values):
            raise ValueError(
                "Invalid value for `name` ({0}), must be one of {1}"  # noqa: E501
                .format(name, allowed_values)
            )

        self._name = name

    @property
    def table_id(self):
        """Gets the table_id of this UniqueConstraintDto.  # noqa: E501

        Id of the table this unique constraint is associated with  # noqa: E501

        :return: The table_id of this UniqueConstraintDto.  # noqa: E501
        :rtype: str
        """
        return self._table_id

    @table_id.setter
    def table_id(self, table_id):
        """Sets the table_id of this UniqueConstraintDto.

        Id of the table this unique constraint is associated with  # noqa: E501

        :param table_id: The table_id of this UniqueConstraintDto.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                table_id is not None and len(table_id) > 100):
            raise ValueError("Invalid value for `table_id`, length must be less than or equal to `100`")  # noqa: E501
        if (self._configuration.client_side_validation and
                table_id is not None and len(table_id) < 0):
            raise ValueError("Invalid value for `table_id`, length must be greater than or equal to `0`")  # noqa: E501

        self._table_id = table_id

    @property
    def values(self):
        """Gets the values of this UniqueConstraintDto.  # noqa: E501

        List of values in the unique constraint  # noqa: E501

        :return: The values of this UniqueConstraintDto.  # noqa: E501
        :rtype: list[str]
        """
        return self._values

    @values.setter
    def values(self, values):
        """Sets the values of this UniqueConstraintDto.

        List of values in the unique constraint  # noqa: E501

        :param values: The values of this UniqueConstraintDto.  # noqa: E501
        :type: list[str]
        """

        self._values = values

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UniqueConstraintDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UniqueConstraintDto):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UniqueConstraintDto):
            return True

        return self.to_dict() != other.to_dict()
